### ISSUE TITLE
Canvas's border is invisible

### ISSUE THREAD

**Issue by bqpd** [mmou/tacit#16]
![image](https://cloud.githubusercontent.com/assets/1482776/7280776/1ec95a14-e8f3-11e4-8212-6372b6e0db28.png)

**Comment by eewayhsu** [comment]
So our padview has a weird space between suggestions due to the toolbar.  We should discuss how we want this to scale and can then make decisions on what kinds of lines, colors we should use to indicate the differences.

**Comment by bqpd** [comment]
Yup. For now, should we put a border around the pad?
