### ISSUE TITLE
Move cursor for every tool

### ISSUE THREAD

**Issue by bqpd** [mmou/tacit#17]
![image](https://cloud.githubusercontent.com/assets/1482776/7280800/43d92758-e8f3-11e4-84cd-541a2f7abec1.png)

**Comment by eewayhsu** [comment]
I was going to just set the cursor in PadView in the index.js and toolbar.js, but this doesn't seem to work.  It only does the different cursor on the nodes and things and right outside the SVG area.  Help?

**Comment by bqpd** [comment]
Try removing the lines in `sketch.css` that specifiy cursors.

**Comment by bqpd** [comment]
Confirmed, that works for me.

**Comment by eewayhsu** [comment]
oh yay. yeah works for me too :P okay well I'll add that soon.

**Comment by bqpd** [comment]
My bad, shouldn't have left that in there...
