### ISSUE TITLE
Purple Beams

### ISSUE THREAD

**Issue by bqpd** [mmou/tacit#18]
![image](https://cloud.githubusercontent.com/assets/1482776/7280811/5127b834-e8f3-11e4-8f51-021ca9cf1934.png)

**Comment by mmou** [comment]
jessica: "What does it mean when I highlight points/lines?"

we should remove blue+red beam colors

**Comment by olearym** [comment]
![screen shot 2015-05-02 at 6 07 12 pm](https://cloud.githubusercontent.com/assets/3387032/7442947/1cad8c22-f0f6-11e4-99c4-1c45f7a575e3.png)
![screen shot 2015-05-02 at 6 06 57 pm](https://cloud.githubusercontent.com/assets/3387032/7442948/1eeb672a-f0f6-11e4-9778-10db01bdbace.png)

Hm. I don't like the way this looks with either of the brown colors. I think the beam color should be different from the node color, too. Can we just make all unselected beams blue?

**Comment by bqpd** [comment]
How's it look?

**Comment by olearym** [comment]
This is how it looks with blue.

![screen shot 2015-05-02 at 6 10 35 pm](https://cloud.githubusercontent.com/assets/3387032/7442955/91a4482c-f0f6-11e4-9d3e-5b074515ec01.png)

**Comment by eewayhsu** [comment]
I actually prefer the second brown.  Just because the blue is super bright. How do people feel about a slightly more neutral or earthy color?  (despite the tacit._blue_)

**Comment by olearym** [comment]
I agree that the blue is super bright. Still, I think I prefer it to the brown - for some reason the brown just looks kind of gross to me. Maybe there's a less saturated blue we could use? I'm going to leave it blue for now, it's an easy enough fix if we don't like it.

**Comment by bqpd** [comment]
I like brown and blue alike! But those critiques make sense. Let's definitely play with the color.
