### ISSUE TITLE
Changing the color of something back to what it was produces new suggestions

### ISSUE THREAD

**Issue by bqpd** [mmou/tacit#25]
![image](https://cloud.githubusercontent.com/assets/1482776/7280876/c670c41e-e8f3-11e4-88f9-824674f5c979.png)

**Comment by eewayhsu** [comment]
true, on every click regardless if something new happens, we get new suggestions.  What are opinions on this one?

**Comment by bqpd** [comment]
I sometimes do this intentionally but I'm weird.

**Comment by olearym** [comment]
Ned did this in master.
