### ISSUE TITLE
Scrolling doesn't work inside the canvas

### ISSUE THREAD

**Issue by bqpd** [mmou/tacit#26]
![image](https://cloud.githubusercontent.com/assets/1482776/7280878/d09def7a-e8f3-11e4-81dc-5ac7d7bd837c.png)

**Comment by eewayhsu** [comment]
Will we be supporting scrolling inside the canvas?  I think that we should just limit our window and where things can be dragged/made.  No scrolling.

**Comment by bqpd** [comment]
I agree, but think that this might require positioning suggestions vertically on a widescreen, and auto-limiting the number of suggestions. I hear boostrap is good at the former?

**Comment by bqpd** [comment]
Not an issue once we fix layout to not require scrolling!
