### ISSUE TITLE
Finger pointer on logo

### ISSUE THREAD

**Issue by bqpd** [mmou/tacit#27]
![image](https://cloud.githubusercontent.com/assets/1482776/7280889/de103d66-e8f3-11e4-9e16-bad9473cdd7a.png)

**Comment by eewayhsu** [comment]
What do you guys think it should do?  Currently it is indeed clickable, but just brings you to whatever page you are already on.

**Comment by bqpd** [comment]
It could reload the page, and hence the drawing?

**Comment by eewayhsu** [comment]
But wouldn't that be very unsafe because we have no real save button?  What hard work lost.  
I don't really have a better idea though.  Like besides what if it set your cursors to the default or something.  Also I think our default cursor should be first in the list.

**Comment by bqpd** [comment]
If they click the root logo, what were they expecting? Eventually we'll autosave.

Agreed with first in the list.

**Comment by bqpd** [comment]
MEGAN HAS OPINIONS ABOUT THIS

**Comment by bqpd** [comment]
ASSIGNED TO: ANYONE BUT ME BECAUSE I DON'T CARE

**Comment by olearym** [comment]
I'll take this one! Plan is to make picture still exist but not clickable.
