### ISSUE TITLE
"Brown" is not colored in tutorial

### ISSUE THREAD

**Issue by bqpd** [mmou/tacit#28]
![image](https://cloud.githubusercontent.com/assets/1482776/7280892/eb797986-e8f3-11e4-9a3e-d4f6d9367b42.png)

**Comment by eewayhsu** [comment]
Oh, the brown dotted lines.  Should we fix this?  I assume our tutorial will be completely different in the final iteration.

**Comment by bqpd** [comment]
Worth fixing, yeah, but lowest priority.
