### ISSUE TITLE
Feedback from GR4 presentation

### ISSUE THREAD

**Issue by bqpd** [mmou/tacit#30]
Coordinate system in pad - would be nice
Pad borders? - please delineate
Highlight diffs in suggestions - probably not possible (but cool idea..)
Icons cartoonish? - idk. i personally think that yes they are absurdly/comically large.
Tutorial !!! - important!! learnability is important
Drawing ground line - should do this
How to show points under greatest stress? (...) - not sure what this meant....
Hover over tools - show name - yeah good thing to do!

~

from jessica:

Wiki presentation: Great description of shallow parts!
Fidelity: Would have liked to see higher fidelity in look and feel for the suggestions pane.
Usability: Drawing often goes off screen, even when moved back, clicking on suggested drawings moves it back (http://puu.sh/hn8of/79d02dc7e7.png). Icon tooltips would be useful, e.g. on hover, display name of icon. Drawing gets tedious when arrows are close together. Not clear to user where boundaries of drawing canvas are. What does it mean when I highlight points/lines? Change cursor for each icon. Interface is very much left justified, would be better to balance out user's field of vision - one suggestion would be to move the suggested pane to the right side and stretch the drawing area to fill the height and rest of the width. 
Overall: Great implementation, your project is definitely one of the most challenging ones on that front. Would focus on fleshing out the possible use cases of the drawing and the suggestions panel.

**Comment by mmou** [comment]
cleaning up to things that haven't been made into issues, because they are currently out of our scope / are "nice to have". everything else that needs to be addressed have been made into issues.

Highlight diffs in suggestions - probably not possible (but cool idea..)
How to show points under greatest stress? (...) - not sure what this meant....
Drawing gets tedious when arrows are close together. 

Would focus on fleshing out the possible use cases of the drawing and the suggestions panel.

**Comment by bqpd** [comment]
Agreed! re: 3 up there, We could have a way to turn display of the arrows off?

**Comment by eewayhsu** [comment]
Yup turning the arrow displays off would be nice.

**Comment by bqpd** [comment]
We should turn these into clearer issues!

**Comment by bqpd** [comment]
This seems closeable. Reopen if you disagree!

**Comment by bqpd** [comment]
@mmou and I were talking about the right place for display options...the
title bar, maybe?
