### ISSUE TITLE
Ground line / background

### ISSUE THREAD

**Issue by eewayhsu** [mmou/tacit#33]
Add a ground line or background to give users a better perspective on their design.

**Comment by bqpd** [comment]
potentially a grid!

**Comment by eewayhsu** [comment]
Must edit how suggestions are made? to remove the gridlines from there as well.  Persistent

**Comment by bqpd** [comment]
Ah, yeah. There's a bit in `suggestions.js` that changes the nodesize to 0; in that same place you could change the background?

**Comment by eewayhsu** [comment]
Yup :D interestingly tho sometimes the suggestion goes out of range right and then it just becomes unclickable.  Will look into issue.

**Comment by bqpd** [comment]
whoa, odd.

**Comment by eewayhsu** [comment]
Also when we drag the object, it is moving the whole sketchpad as opposed to the location of the object (in the sense that we can never change the location of the object with respect to the ground line).

**Comment by eewayhsu** [comment]
Also since suggestions don't seem to be centered at the same point as our current drawing, when we click through suggestions, our grid changes with respect to the screen because it always has the object left dot as 0,0? Or something similar to that.

**Comment by bqpd** [comment]
As for dragging, just drag the nodes individually and you can move the drawing.

Oh, yeah. Suggestions should probably be better scaled / translated.

**Comment by eewayhsu** [comment]
![screen shot 2015-05-02 at 6 26 10 pm](https://cloud.githubusercontent.com/assets/3779116/7443000/01e01074-f0f9-11e4-98f4-b048e9ae741e.png)
![screen shot 2015-05-02 at 6 27 04 pm](https://cloud.githubusercontent.com/assets/3779116/7443001/02d7c3dc-f0f9-11e4-9175-c2dcb0daa0ab.png)

ex. 
Here the grid from picture 1 is shifted from picture 2. 
and also the last suggestion error. 

Also selecting off-screen suggestion --> 

![screen shot 2015-05-02 at 6 29 50 pm](https://cloud.githubusercontent.com/assets/3779116/7443005/44222756-f0f9-11e4-93db-11b99c87a71b.png)

**Comment by bqpd** [comment]
Huh, interesting. I wonder why the suggestions are translating, they should be centering...

**Comment by mmou** [comment]
another bug: after you've clicked on a suggestion, you cannot toggle grid/base line anymore

**Comment by mmou** [comment]
another bug: i really don't like that the grid changes size/position when a suggestion or old version is loaded

**Comment by eewayhsu** [comment]
So the grid should be the same size, though it does change location because of where the fixed point is located I believe. Will come up with solution.

**Comment by eewayhsu** [comment]
Also I see. For the toggle thing it's interesting because I haven't looked too much on how suggestions are used in the actual sketch. However if you retain a grid inside the sketch you can toggle on and off the grid after pressing selection (though grid always exists in suggestions). Will look into how svgs refresh or whatnot

**Comment by bqpd** [comment]
I think I fixed this, at least for suggestions, in #48.

**Comment by eewayhsu** [comment]
font-size: 3em; line-height: 0.75; this in sketch.coffee breaks the grid 

why is that there?

**Comment by eewayhsu** [comment]
Undo-redo messes with the grid because we need to decide whether undo can let you go to a different sketch.  (because if we checked no grid and then undo to a different sketch with a grid, our checkbox does not automatically get checked again).

**Comment by eewayhsu** [comment]
(and when we press suggestions, do we always start with a grid and groundline regardless of what the user previously set?)

**Comment by bqpd** [comment]
WORKS
