### ISSUE TITLE
Cursor sometimes changes to a regular pointer after dragging around selecting things. 

### ISSUE THREAD

**Issue by eewayhsu** [mmou/tacit#43]

**Comment by eewayhsu** [comment]
Oh changes after a certain amount of time.

**Comment by eewayhsu** [comment]
http://stackoverflow.com/questions/27792197/custom-cursor-image-disappears-after-clicking-anywhere-in-page-mac-multiple-br

JK.  cannot reproduce in other situations.  won't fix.

**Comment by bqpd** [comment]
Wat. It's a MS Word issue??
