### ISSUE TITLE
when you have scrolled all the way to the right of the versions, and save another version, the scrollbar doesn't automatically scroll all the way to the right

### ISSUE THREAD

**Issue by mmou** [mmou/tacit#58]

**Comment by bqpd** [comment]
Could not reproduce, though Eeway and I had a good discussion about what the intended behaviour is.

To wit: if scroll bar is showing the last element, then adding new ones scrolls all the way to the right.

If it's not, though, we leave it be, presuming the user wanted to compare their current drawing to some in the past.
